import React, { useState } from 'react';
import {
  Box,
  Button,
  TextField,
  Typography,
  Paper,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  Grid,
  Card,
  CardContent,
  Divider,
  LinearProgress,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from '@mui/material';
import {
  Assessment,
  FileDownload,
  TrendingUp,
  TrendingDown,
  AccountBalance,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import ep1 from '../api/ep1';
import global1 from './global1';
import * as XLSX from 'xlsx';

const StudentLedgerReportPageds = () => {
  const navigate = useNavigate();
  const [regno, setRegno] = useState('');
  const [semester, setSemester] = useState(''); // Empty means all semesters
  const [ledgerData, setLedgerData] = useState(null);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [reportGenerated, setReportGenerated] = useState(false);

  const semesters = ['1', '2', '3', '4', '5', '6', '7', '8'];

  const handleGenerateReport = async () => {
    if (!regno) {
      setError('Please enter Registration Number');
      return;
    }

    setLoading(true);
    setError('');
    setReportGenerated(false);

    try {
      // Build URL with optional semester parameter
      let url = `/api/v2/studentledgerreportds?regno=${regno}&colid=${global1.colid}`;
      if (semester) {
        url += `&semester=${semester}`;
      }

      const response = await ep1.get(url);

      if (response.data.success) {
        setLedgerData(response.data.data);
        setSummary(response.data.data.summary);
        setReportGenerated(true);
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Error generating report');
    } finally {
      setLoading(false);
    }
  };

  const handleExportToExcel = () => {
    if (!ledgerData) {
      setError('No data to export');
      return;
    }

    const excelData = [
      ['STUDENT FEE LEDGER REPORT'],
      [''],
      ['Student Name', ledgerData.student.name],
      ['Registration Number', ledgerData.student.regno],
      ['Semester', ledgerData.student.semester],
      ['College ID', ledgerData.student.colid],
      [''],
      ['Date', 'Fee Item', 'Category', 'Semester', 'Amount', 'Type', 'Payment Mode', 'Details'],
      ...ledgerData.transactions.map((txn) => [
        new Date(txn.createdAt).toLocaleDateString('en-IN'),
        txn.feeitem || '',
        txn.feecategory || '',
        txn.semester || '',
        txn.amount,
        txn.amount > 0 ? 'Payable' : 'Paid',
        txn.paymode || '',
        txn.paydetails || '',
      ]),
      [''],
      ['SUMMARY'],
      ['Total Payable', summary.totalPayable.toFixed(2)],
      ['Total Paid', summary.totalPaid.toFixed(2)],
      ['Balance Due', summary.balance.toFixed(2)],
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(excelData);
    XLSX.utils.book_append_sheet(wb, ws, 'Student Ledger');
    XLSX.writeFile(wb, `StudentLedger_${regno}_${semester || 'All'}.xlsx`);
  };

  return (
    <Box sx={{ p: 3, bgcolor: '#f5f5f5', minHeight: '100vh' }}>
      {/* Header Section */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold', mb: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
          <Assessment sx={{ fontSize: 32, color: '#1976d2' }} />
          STUDENT FEE LEDGER REPORT
        </Typography>
        <Typography variant="body2" sx={{ color: '#666' }}>
          {global1.name}
        </Typography>
        <Typography variant="body2" sx={{ color: '#666' }}>
          Generated by: {global1.user} | {new Date().toLocaleDateString('en-IN')}
        </Typography>
      </Box>

      {/* Filter Section */}
      <Paper sx={{ p: 3, mb: 3, borderRadius: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2 }}>
          Report Configuration
        </Typography>

        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Registration Number *"
              value={regno}
              onChange={(e) => setRegno(e.target.value)}
              placeholder="Enter student registration number"
              size="small"
              required
            />
          </Grid>

          <Grid item xs={12} sm={12}>
            <FormControl fullWidth size="medium">
              <InputLabel size='medium'>Semester</InputLabel>
              <Select
                value={semester}
                onChange={(e) => setSemester(e.target.value)}
                label="Semester (Optional)"
              >
                <MenuItem value="">All Semesters</MenuItem>
                {semesters.map((sem) => (
                  <MenuItem key={sem} value={sem}>
                    Semester {sem}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>
        </Grid>

        <Button
          variant="contained"
          onClick={handleGenerateReport}
          disabled={loading}
          sx={{ mb: 2 }}
        >
          {loading ? 'Generating...' : 'Generate Report'}
        </Button>

        {loading && (
          <Box sx={{ mt: 2 }}>
            <LinearProgress />
            <Typography variant="body2" sx={{ mt: 1, color: '#1976d2' }}>
              Fetching student ledger data...
            </Typography>
          </Box>
        )}

        {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
      </Paper>

      {/* Summary Cards */}
      {summary && reportGenerated && (
        <Grid container spacing={2} sx={{ mb: 3 }}>
          <Grid item xs={12} sm={6} md={3}>
            <Card sx={{ boxShadow: 2 }}>
              <CardContent sx={{ textAlign: 'center' }}>
                <Typography variant="body2" sx={{ color: '#666', mb: 1 }}>
                  Total Payable
                </Typography>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                  <TrendingUp sx={{ color: '#ff9800', fontSize: 28 }} />
                  <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#ff9800' }}>
                    ₹ {summary.totalPayable.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card sx={{ boxShadow: 2 }}>
              <CardContent sx={{ textAlign: 'center' }}>
                <Typography variant="body2" sx={{ color: '#666', mb: 1 }}>
                  Total Paid
                </Typography>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                  <TrendingDown sx={{ color: '#4caf50', fontSize: 28 }} />
                  <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#4caf50' }}>
                    ₹ {summary.totalPaid.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card sx={{ boxShadow: 2 }}>
              <CardContent sx={{ textAlign: 'center' }}>
                <Typography variant="body2" sx={{ color: '#666', mb: 1 }}>
                  Balance Due
                </Typography>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                  <AccountBalance sx={{ color: summary.balance > 0 ? '#f44336' : '#4caf50', fontSize: 28 }} />
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: 'bold',
                      color: summary.balance > 0 ? '#f44336' : '#4caf50',
                    }}
                  >
                    ₹ {summary.balance.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card sx={{ boxShadow: 2 }}>
              <CardContent sx={{ textAlign: 'center' }}>
                <Typography variant="body2" sx={{ color: '#666', mb: 1 }}>
                  Transactions
                </Typography>
                <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#1976d2' }}>
                  {summary.transactionCount}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      )}

      {/* Ledger Details */}
      {reportGenerated && ledgerData && (
        <Paper sx={{ p: 3, borderRadius: 2 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
              LEDGER DETAILS
            </Typography>
            <Button
              variant="outlined"
              startIcon={<FileDownload />}
              onClick={handleExportToExcel}
            >
              Export Excel
            </Button>
          </Box>

          <Divider sx={{ mb: 2 }} />

          {/* Student Info */}
          <Box sx={{ mb: 3 }}>
            <Grid container spacing={2}>
              <Grid item xs={12} sm={6}>
                <Typography variant="body2" sx={{ color: '#666' }}>
                  <strong>Student Name:</strong> {ledgerData.student.name}
                </Typography>
                <Typography variant="body2" sx={{ color: '#666' }}>
                  <strong>Registration Number:</strong> {ledgerData.student.regno}
                </Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="body2" sx={{ color: '#666' }}>
                  <strong>Semester:</strong> {ledgerData.student.semester}
                </Typography>
                <Typography variant="body2" sx={{ color: '#666' }}>
                  <strong>As On:</strong> {new Date().toLocaleDateString('en-IN')}
                </Typography>
              </Grid>
            </Grid>
          </Box>

          <Divider sx={{ mb: 2 }} />

          {/* Transactions Table */}
          <TableContainer>
            <Table>
              <TableHead sx={{ bgcolor: '#f5f5f5' }}>
                <TableRow>
                  <TableCell sx={{ fontWeight: 'bold' }}>Date</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Fee Item</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Category</TableCell>
                  {!semester && <TableCell sx={{ fontWeight: 'bold' }}>Semester</TableCell>}
                  <TableCell sx={{ fontWeight: 'bold' }} align="right">
                    Amount
                  </TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }} align="center">
                    Type
                  </TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Payment Mode</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Details</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {ledgerData.transactions.length > 0 ? (
                  ledgerData.transactions.map((txn, index) => (
                    <TableRow key={index} hover>
                      <TableCell>
                        {new Date(txn.createdAt).toLocaleDateString('en-IN')}
                      </TableCell>
                      <TableCell>{txn.feeitem || '-'}</TableCell>
                      <TableCell>{txn.feecategory || '-'}</TableCell>
                      {!semester && <TableCell>{txn.semester || '-'}</TableCell>}
                      <TableCell align="right">
                        <Typography
                          sx={{
                            color: txn.amount > 0 ? '#ff9800' : '#4caf50',
                            fontWeight: 'bold',
                          }}
                        >
                          ₹ {txn.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                        </Typography>
                      </TableCell>
                      <TableCell align="center">
                        <Typography
                          sx={{
                            bgcolor: txn.amount > 0 ? '#fff3e0' : '#e8f5e9',
                            color: txn.amount > 0 ? '#f57c00' : '#2e7d32',
                            padding: '4px 8px',
                            borderRadius: 1,
                            fontSize: '0.85rem',
                            fontWeight: 'bold',
                            textAlign: 'center',
                          }}
                        >
                          {txn.amount > 0 ? 'Payable' : 'Paid'}
                        </Typography>
                      </TableCell>
                      <TableCell>{txn.paymode || '-'}</TableCell>
                      <TableCell>{txn.paydetails || '-'}</TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={semester ? 7 : 8} align="center">
                      No transactions found
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>

          {/* Summary Footer */}
          <Box sx={{ mt: 3, pt: 2, borderTop: '2px solid #ddd' }}>
            <Grid container spacing={2}>
              <Grid item xs={12} sm={6} md={3}>
                <Box sx={{ textAlign: 'right' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Total Payable
                  </Typography>
                  <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#ff9800' }}>
                    ₹ {summary.totalPayable.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Box sx={{ textAlign: 'right' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Total Paid
                  </Typography>
                  <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#4caf50' }}>
                    ₹ {summary.totalPaid.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Box sx={{ textAlign: 'right' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Balance Due
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: 'bold',
                      color: summary.balance > 0 ? '#f44336' : '#4caf50',
                    }}
                  >
                    ₹ {summary.balance.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Box sx={{ textAlign: 'right' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Transactions
                  </Typography>
                  <Typography variant="h6" sx={{ fontWeight: 'bold', color: '#1976d2' }}>
                    {summary.transactionCount}
                  </Typography>
                </Box>
              </Grid>
            </Grid>
          </Box>

          {/* Footer */}
          <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid #ddd', textAlign: 'center' }}>
            <Typography variant="caption" sx={{ color: '#999' }}>
              Report generated on {new Date().toLocaleString('en-IN')} | Prepared by: {global1.user}
            </Typography>
          </Box>
        </Paper>
      )}

      {/* No Data Message */}
      {reportGenerated && !ledgerData && (
        <Paper sx={{ p: 3, textAlign: 'center' }}>
          <Typography variant="h6" sx={{ color: '#999' }}>
            No Ledger Data Found
          </Typography>
          <Typography variant="body2" sx={{ color: '#ccc', mt: 1 }}>
            No fee transactions found for this student in the selected criteria.
          </Typography>
        </Paper>
      )}
    </Box>
  );
};

export default StudentLedgerReportPageds;
