import React, { useState } from "react";
import {
  Box,
  Button,
  TextField,
  Typography,
  Paper,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  Grid,
  Card,
  CardContent,
  Divider,
  LinearProgress,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tabs,
  Tab,
  Chip,
} from "@mui/material";
import {
  Assessment,
  FileDownload,
  TrendingUp,
  TrendingDown,
  AccountBalance,
  People,
  Close,
  SearchOff,
  ArrowBack,
} from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import ep1 from "../api/ep1";
import global1 from "./global1";
import * as XLSX from "xlsx";

const CollegeStudentLedgerReportPageds = () => {
  const navigate = useNavigate();
  const [programcode, setProgramcode] = useState("");
  const [academicyear, setAcademicyear] = useState("");
  const [semester, setSemester] = useState("");
  const [classdate, setClassdate] = useState("");
  const [ledgerData, setLedgerData] = useState(null);
  const [overallSummary, setOverallSummary] = useState(null);
  const [studentSummary, setStudentSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [reportGenerated, setReportGenerated] = useState(false);
  const [tabValue, setTabValue] = useState(0);
  const [filters, setFilters] = useState({});

  const semesters = ["1", "2", "3", "4", "5", "6", "7", "8"];
  const years = [
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25",
    "2025-26",
    "2026-27",
    "2027-28",
    "2028-29",
  ];

  const handleGenerateReport = async () => {
    setLoading(true);
    setError("");
    setReportGenerated(false);

    try {
      let url = `/api/v2/collegerepledgerreportds?colid=${global1.colid}`;

      if (programcode && programcode.trim())
        url += `&programcode=${encodeURIComponent(programcode.trim())}`;
      if (academicyear && academicyear.trim())
        url += `&academicyear=${encodeURIComponent(academicyear.trim())}`;
      if (semester && semester.trim())
        url += `&semester=${encodeURIComponent(semester.trim())}`;
      if (classdate && classdate.trim())
        url += `&classdate=${encodeURIComponent(classdate.trim())}`;

      console.log("Request URL:", url);

      const response = await ep1.get(url);

      console.log("Response:", response.data);

      if (response.data.success) {
        setLedgerData(response.data.data.transactions || []);
        setStudentSummary(response.data.data.studentSummary || []);
        setOverallSummary(response.data.data.overallSummary);
        setFilters(response.data.data.filters);
        setReportGenerated(true);
        setTabValue(0);

        if (
          !response.data.data.transactions ||
          response.data.data.transactions.length === 0
        ) {
          setError(
            "No records found for the specified filters. Try different criteria."
          );
        }
      }
    } catch (err) {
      console.error("Error:", err);
      setError(
        err.response?.data?.message ||
          "Error generating report. Please check filters and try again."
      );
    } finally {
      setLoading(false);
    }
  };

  const clearFilters = () => {
    setProgramcode("");
    setAcademicyear("");
    setSemester("");
    setClassdate("");
    setError("");
  };

  const handleExportToExcel = () => {
    if (!ledgerData || ledgerData.length === 0) {
      setError("No data to export");
      return;
    }

    const excelData = [
      ["COLLEGE STUDENT FEE LEDGER REPORT"],
      [""],
      ["Report Filters:"],
      ["Program Code", filters.programcode],
      ["Academic Year", filters.academicyear],
      ["Semester", filters.semester],
      ["Due Date", filters.classdate],
      ["Generated On", new Date().toLocaleDateString("en-IN")],
      ["Generated By", global1.user],
      [""],
      ["OVERALL SUMMARY"],
      ["Total Payable", overallSummary.totalPayable.toFixed(2)],
      ["Total Paid", overallSummary.totalPaid.toFixed(2)],
      ["Balance Due", overallSummary.balance.toFixed(2)],
      ["Total Transactions", overallSummary.totalTransactions],
      ["Unique Students", overallSummary.uniqueStudents],
      [""],
      ["STUDENT SUMMARY"],
      [
        "Student Name",
        "Reg No",
        "Program Code",
        "Semester",
        "Total Payable",
        "Total Paid",
        "Balance",
        "Transactions",
      ],
      ...studentSummary.map((student) => [
        student._id.name,
        student._id.regno,
        student._id.programcode || "",
        student._id.semester || "",
        student.totalPayable.toFixed(2),
        student.totalPaid.toFixed(2),
        student.balance.toFixed(2),
        student.transactionCount,
      ]),
      [""],
      ["DETAILED TRANSACTIONS"],
      [
        "Date",
        "Student Name",
        "Reg No",
        "Fee Item",
        "Category",
        "Amount",
        "Type",
        "Payment Mode",
        "Status",
      ],
      ...ledgerData.map((txn) => [
        new Date(txn.classdate).toLocaleDateString("en-IN"),
        txn.name,
        txn.regno,
        txn.feeitem || "",
        txn.feecategory || "",
        txn.amount,
        txn.amount > 0 ? "Payable" : "Paid",
        txn.paymode || "",
        txn.status || "",
      ]),
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(excelData);
    XLSX.utils.book_append_sheet(wb, ws, "College Ledger Report");
    XLSX.writeFile(wb, `CollegeLedgerReport_${new Date().getTime()}.xlsx`);
  };

  return (
    <Box sx={{ p: 3, bgcolor: "#f5f5f5", minHeight: "100vh" }}>
      <Box sx={{ mb: 3, display: "flex", alignItems: "center", gap: 2 }}>
        <Button
          startIcon={<ArrowBack />}
          onClick={() => navigate("/dashdashfacnew")}
        >
          Back
        </Button>
      </Box>
      {/* Header Section */}
      <Box sx={{ mb: 3 }}>
        <Typography
          variant="h4"
          sx={{
            fontWeight: "bold",
            mb: 1,
            display: "flex",
            alignItems: "center",
            gap: 1,
          }}
        >
          <Assessment sx={{ fontSize: 32, color: "#1976d2" }} />
          COLLEGE STUDENT FEE LEDGER REPORT
        </Typography>
        <Typography variant="body2" sx={{ color: "#666" }}>
          {global1.name}
        </Typography>
        <Typography variant="body2" sx={{ color: "#666" }}>
          Generated by: {global1.user} |{" "}
          {new Date().toLocaleDateString("en-IN")}
        </Typography>
      </Box>

      {/* Filter Section */}
      <Paper sx={{ p: 3, mb: 3, borderRadius: 2 }}>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            mb: 2,
          }}
        >
          <Typography variant="h6" sx={{ fontWeight: "bold" }}>
            Report Filters
          </Typography>
          {(programcode || academicyear || semester || classdate) && (
            <Button
              size="small"
              variant="outlined"
              startIcon={<Close />}
              onClick={clearFilters}
              color="secondary"
            >
              Clear Filters
            </Button>
          )}
        </Box>

        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={12} sm={6} md={3}>
            <TextField
              fullWidth
              label="Program Code"
              value={programcode}
              onChange={(e) => setProgramcode(e.target.value)}
              placeholder="e.g., CS001"
              size="small"
            />
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <FormControl fullWidth size="small">
              <InputLabel>Academic Year</InputLabel>
              <Select
                value={academicyear}
                onChange={(e) => setAcademicyear(e.target.value)}
                label="Academic Year"
              >
                <MenuItem value="">All Years</MenuItem>
                {years.map((year) => (
                  <MenuItem key={year} value={year}>
                    {year}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <FormControl fullWidth size="small">
              <InputLabel>Semester</InputLabel>
              <Select
                value={semester}
                onChange={(e) => setSemester(e.target.value)}
                label="Semester"
              >
                <MenuItem value="">All Semesters</MenuItem>
                {semesters.map((sem) => (
                  <MenuItem key={sem} value={sem}>
                    Semester {sem}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <TextField
              fullWidth
              label="Due Date (On or Before)"
              type="date"
              value={classdate}
              onChange={(e) => setClassdate(e.target.value)}
              InputLabelProps={{ shrink: true }}
              size="small"
            />
          </Grid>
        </Grid>

        {/* Active Filters Display */}
        {(programcode || academicyear || semester || classdate) && (
          <Box sx={{ mb: 2, display: "flex", flexWrap: "wrap", gap: 1 }}>
            {programcode && (
              <Chip
                label={`Program: ${programcode}`}
                onDelete={() => setProgramcode("")}
                size="small"
                color="primary"
                variant="outlined"
              />
            )}
            {academicyear && (
              <Chip
                label={`Year: ${academicyear}-${parseInt(academicyear) + 1}`}
                onDelete={() => setAcademicyear("")}
                size="small"
                color="primary"
                variant="outlined"
              />
            )}
            {semester && (
              <Chip
                label={`Semester: ${semester}`}
                onDelete={() => setSemester("")}
                size="small"
                color="primary"
                variant="outlined"
              />
            )}
            {classdate && (
              <Chip
                label={`Due Date: ${new Date(classdate).toLocaleDateString(
                  "en-IN"
                )}`}
                onDelete={() => setClassdate("")}
                size="small"
                color="primary"
                variant="outlined"
              />
            )}
          </Box>
        )}

        <Button
          variant="contained"
          onClick={handleGenerateReport}
          disabled={loading}
        >
          {loading ? "Generating..." : "Generate Report"}
        </Button>

        {loading && (
          <Box sx={{ mt: 2 }}>
            <LinearProgress />
            <Typography variant="body2" sx={{ mt: 1, color: "#1976d2" }}>
              Fetching college ledger data...
            </Typography>
          </Box>
        )}

        {error && (
          <Alert
            severity={
              reportGenerated && (!ledgerData || ledgerData.length === 0)
                ? "info"
                : "error"
            }
            sx={{ mt: 2 }}
          >
            {error}
          </Alert>
        )}
      </Paper>

      {/* Summary Cards */}
      {overallSummary &&
        reportGenerated &&
        ledgerData &&
        ledgerData.length > 0 && (
          <Grid container spacing={2} sx={{ mb: 3 }}>
            <Grid item xs={12} sm={6} md={2.4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: "center", p: 2 }}>
                  <Typography variant="body2" sx={{ color: "#666", mb: 1 }}>
                    Total Payable
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{ fontWeight: "bold", color: "#ff9800" }}
                  >
                    ₹{" "}
                    {overallSummary.totalPayable.toLocaleString("en-IN", {
                      maximumFractionDigits: 0,
                    })}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} sm={6} md={2.4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: "center", p: 2 }}>
                  <Typography variant="body2" sx={{ color: "#666", mb: 1 }}>
                    Total Paid
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{ fontWeight: "bold", color: "#4caf50" }}
                  >
                    ₹{" "}
                    {overallSummary.totalPaid.toLocaleString("en-IN", {
                      maximumFractionDigits: 0,
                    })}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} sm={6} md={2.4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: "center", p: 2 }}>
                  <Typography variant="body2" sx={{ color: "#666", mb: 1 }}>
                    Balance Due
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: "bold",
                      color: overallSummary.balance > 0 ? "#f44336" : "#4caf50",
                    }}
                  >
                    ₹{" "}
                    {overallSummary.balance.toLocaleString("en-IN", {
                      maximumFractionDigits: 0,
                    })}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} sm={6} md={2.4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: "center", p: 2 }}>
                  <Typography variant="body2" sx={{ color: "#666", mb: 1 }}>
                    Transactions
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{ fontWeight: "bold", color: "#1976d2" }}
                  >
                    {overallSummary.totalTransactions}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} sm={6} md={2.4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: "center", p: 2 }}>
                  <Typography
                    variant="body2"
                    sx={{
                      color: "#666",
                      mb: 1,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      gap: 0.5,
                    }}
                  >
                    <People sx={{ fontSize: 16 }} />
                    Students
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{ fontWeight: "bold", color: "#9c27b0" }}
                  >
                    {overallSummary.uniqueStudents}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        )}

      {/* Tabbed Section */}
      {reportGenerated && ledgerData && ledgerData.length > 0 && (
        <Paper sx={{ borderRadius: 2, boxShadow: 2 }}>
          <Tabs
            value={tabValue}
            onChange={(e, newValue) => setTabValue(newValue)}
            sx={{ borderBottom: 1, borderColor: "divider" }}
          >
            <Tab label={`Student Summary (${studentSummary?.length || 0})`} />
            <Tab label={`All Transactions (${ledgerData?.length || 0})`} />
          </Tabs>

          <Box sx={{ p: 3 }}>
            {/* Tab 1: Student Summary */}
            {tabValue === 0 && (
              <Box>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    mb: 2,
                  }}
                >
                  <Typography variant="h6" sx={{ fontWeight: "bold" }}>
                    STUDENT-WISE SUMMARY
                  </Typography>
                  <Button
                    variant="outlined"
                    startIcon={<FileDownload />}
                    onClick={handleExportToExcel}
                  >
                    Export Excel
                  </Button>
                </Box>

                <TableContainer>
                  <Table size="small">
                    <TableHead sx={{ bgcolor: "#f5f5f5" }}>
                      <TableRow>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Student Name
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Reg No
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Program
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Semester
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="right">
                          Payable
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="right">
                          Paid
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="right">
                          Balance
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="center">
                          Txns
                        </TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {studentSummary && studentSummary.length > 0 ? (
                        studentSummary.map((student, index) => (
                          <TableRow key={index} hover>
                            <TableCell>{student._id.name}</TableCell>
                            <TableCell>{student._id.regno}</TableCell>
                            <TableCell>
                              {student._id.programcode || "-"}
                            </TableCell>
                            <TableCell>{student._id.semester || "-"}</TableCell>
                            <TableCell
                              align="right"
                              sx={{ color: "#ff9800", fontWeight: "bold" }}
                            >
                              ₹{" "}
                              {student.totalPayable.toLocaleString("en-IN", {
                                minimumFractionDigits: 2,
                              })}
                            </TableCell>
                            <TableCell
                              align="right"
                              sx={{ color: "#4caf50", fontWeight: "bold" }}
                            >
                              ₹{" "}
                              {student.totalPaid.toLocaleString("en-IN", {
                                minimumFractionDigits: 2,
                              })}
                            </TableCell>
                            <TableCell
                              align="right"
                              sx={{
                                color:
                                  student.balance > 0 ? "#f44336" : "#4caf50",
                                fontWeight: "bold",
                              }}
                            >
                              ₹{" "}
                              {student.balance.toLocaleString("en-IN", {
                                minimumFractionDigits: 2,
                              })}
                            </TableCell>
                            <TableCell align="center">
                              {student.transactionCount}
                            </TableCell>
                          </TableRow>
                        ))
                      ) : (
                        <TableRow>
                          <TableCell colSpan={8} align="center">
                            No data found
                          </TableCell>
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                </TableContainer>
              </Box>
            )}

            {/* Tab 2: All Transactions */}
            {tabValue === 1 && (
              <Box>
                <Typography variant="h6" sx={{ fontWeight: "bold", mb: 2 }}>
                  DETAILED TRANSACTIONS
                </Typography>

                <TableContainer>
                  <Table size="small">
                    <TableHead sx={{ bgcolor: "#f5f5f5" }}>
                      <TableRow>
                        <TableCell sx={{ fontWeight: "bold" }}>Date</TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Student
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Reg No
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Fee Item
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Category
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="right">
                          Amount
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }} align="center">
                          Type
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Payment Mode
                        </TableCell>
                        <TableCell sx={{ fontWeight: "bold" }}>
                          Status
                        </TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {ledgerData && ledgerData.length > 0 ? (
                        ledgerData.map((txn, index) => (
                          <TableRow key={index} hover>
                            <TableCell>
                              {new Date(txn.classdate).toLocaleDateString(
                                "en-IN"
                              )}
                            </TableCell>
                            <TableCell>{txn.name}</TableCell>
                            <TableCell>{txn.regno}</TableCell>
                            <TableCell>{txn.feeitem || "-"}</TableCell>
                            <TableCell>{txn.feecategory || "-"}</TableCell>
                            <TableCell align="right">
                              <Typography
                                sx={{
                                  color: txn.amount > 0 ? "#ff9800" : "#4caf50",
                                  fontWeight: "bold",
                                }}
                              >
                                ₹{" "}
                                {txn.amount.toLocaleString("en-IN", {
                                  minimumFractionDigits: 2,
                                })}
                              </Typography>
                            </TableCell>
                            <TableCell align="center">
                              <Chip
                                label={txn.amount > 0 ? "Payable" : "Paid"}
                                size="small"
                                color={txn.amount > 0 ? "warning" : "success"}
                                variant="outlined"
                              />
                            </TableCell>
                            <TableCell>{txn.paymode || "-"}</TableCell>
                            <TableCell>
                              <Chip
                                label={txn.status || "Pending"}
                                size="small"
                              />
                            </TableCell>
                          </TableRow>
                        ))
                      ) : (
                        <TableRow>
                          <TableCell colSpan={9} align="center">
                            No transactions found
                          </TableCell>
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                </TableContainer>
              </Box>
            )}
          </Box>

          {/* Summary Footer */}
          {overallSummary && (
            <Box sx={{ p: 3, borderTop: "2px solid #ddd", bgcolor: "#fafafa" }}>
              <Grid container spacing={2}>
                <Grid item xs={12} sm={6} md={2.4}>
                  <Box sx={{ textAlign: "right" }}>
                    <Typography variant="body2" sx={{ color: "#666", mb: 0.5 }}>
                      Total Payable
                    </Typography>
                    <Typography
                      variant="h6"
                      sx={{ fontWeight: "bold", color: "#ff9800" }}
                    >
                      ₹{" "}
                      {overallSummary.totalPayable.toLocaleString("en-IN", {
                        maximumFractionDigits: 0,
                      })}
                    </Typography>
                  </Box>
                </Grid>
                <Grid item xs={12} sm={6} md={2.4}>
                  <Box sx={{ textAlign: "right" }}>
                    <Typography variant="body2" sx={{ color: "#666", mb: 0.5 }}>
                      Total Paid
                    </Typography>
                    <Typography
                      variant="h6"
                      sx={{ fontWeight: "bold", color: "#4caf50" }}
                    >
                      ₹{" "}
                      {overallSummary.totalPaid.toLocaleString("en-IN", {
                        maximumFractionDigits: 0,
                      })}
                    </Typography>
                  </Box>
                </Grid>
                <Grid item xs={12} sm={6} md={2.4}>
                  <Box sx={{ textAlign: "right" }}>
                    <Typography variant="body2" sx={{ color: "#666", mb: 0.5 }}>
                      Balance Due
                    </Typography>
                    <Typography
                      variant="h6"
                      sx={{
                        fontWeight: "bold",
                        color:
                          overallSummary.balance > 0 ? "#f44336" : "#4caf50",
                      }}
                    >
                      ₹{" "}
                      {overallSummary.balance.toLocaleString("en-IN", {
                        maximumFractionDigits: 0,
                      })}
                    </Typography>
                  </Box>
                </Grid>
                <Grid item xs={12} sm={6} md={2.4}>
                  <Box sx={{ textAlign: "right" }}>
                    <Typography variant="body2" sx={{ color: "#666", mb: 0.5 }}>
                      Transactions
                    </Typography>
                    <Typography
                      variant="h6"
                      sx={{ fontWeight: "bold", color: "#1976d2" }}
                    >
                      {overallSummary.totalTransactions}
                    </Typography>
                  </Box>
                </Grid>
                <Grid item xs={12} sm={6} md={2.4}>
                  <Box sx={{ textAlign: "right" }}>
                    <Typography
                      variant="body2"
                      sx={{
                        color: "#666",
                        mb: 0.5,
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "flex-end",
                        gap: 0.5,
                      }}
                    >
                      <People sx={{ fontSize: 16 }} />
                      Students
                    </Typography>
                    <Typography
                      variant="h6"
                      sx={{ fontWeight: "bold", color: "#9c27b0" }}
                    >
                      {overallSummary.uniqueStudents}
                    </Typography>
                  </Box>
                </Grid>
              </Grid>
            </Box>
          )}

          {/* Footer */}
          <Box
            sx={{
              p: 2,
              borderTop: "1px solid #ddd",
              textAlign: "center",
              bgcolor: "#fafafa",
            }}
          >
            <Typography variant="caption" sx={{ color: "#999" }}>
              Report generated on {new Date().toLocaleString("en-IN")} |
              Prepared by: {global1.user}
            </Typography>
          </Box>
        </Paper>
      )}

      {/* No Data Message */}
      {reportGenerated && (!ledgerData || ledgerData.length === 0) && (
        <Paper sx={{ p: 5, textAlign: "center" }}>
          <SearchOff sx={{ fontSize: 64, color: "#ccc", mb: 2 }} />
          <Typography variant="h6" sx={{ color: "#999", mb: 1 }}>
            No Data Found
          </Typography>
          <Typography variant="body2" sx={{ color: "#ccc", mb: 2 }}>
            No fee transactions found for the specified filters.
          </Typography>
        </Paper>
      )}
    </Box>
  );
};

export default CollegeStudentLedgerReportPageds;
