import React, { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Autocomplete,
  Box,
  Button,
  Chip,
  Divider,
  Grid,
  MenuItem,
  Paper,
  Stack,
  TextField,
  Typography
} from "@mui/material";
import { Add, Print, Refresh, Save } from "@mui/icons-material";
import { DataGrid, GridToolbar } from "@mui/x-data-grid";
import ep1 from "../api/ep1";
import global1 from "./global1";
import PlacementCoordinatorShell from "./PlacementCoordinatorShell";

const today = () => new Date().toISOString().slice(0, 10);
const key = (prefix) => `${prefix}-${Date.now()}`;
const text = (value) => String(value || "").trim();
const num = (value) => Number(value || 0);
const currentName = () => global1.name || global1.user || "NA";
const currentUser = () => global1.user || "NA";
const base = () => ({ colid: global1.colid, name: currentName(), user: currentUser() });
const statusOptions = ["Draft", "Submitted", "Approved", "Issued", "Rejected"];

const getRows = async (model, filters = []) => {
  const res = await ep1.get(`/api/v2/purchase2/${model}`, { params: { colid: global1.colid, filters: JSON.stringify(filters) } });
  return res.data?.data || [];
};
const saveRow = async (model, payload) => {
  const res = await ep1.post(`/api/v2/purchase2/${model}`, { ...base(), ...payload });
  return res.data?.data;
};
const updateRow = async (model, row, patch) => saveRow(model, { ...row, id: row._id, ...patch });

function Page({ title, subtitle, children, message, error }) {
  return (
    <PlacementCoordinatorShell title={title}>
      <Box sx={{ mb: 2 }}>
        <Typography variant="h5" fontWeight={800}>{title}</Typography>
        <Typography variant="body2" color="text.secondary">{subtitle}</Typography>
      </Box>
      {message && <Alert severity="success" sx={{ mb: 2 }}>{message}</Alert>}
      {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
      {children}
    </PlacementCoordinatorShell>
  );
}

function PrintBlock({ title, data, children }) {
  if (!data) return null;
  return (
    <Paper className="purchase2-print" sx={{ p: 3, mt: 2, border: "1px solid", borderColor: "divider" }}>
      <style>{`@media print { body * { visibility: hidden; } .purchase2-print, .purchase2-print * { visibility: visible; } .purchase2-print { position: absolute; left: 0; top: 0; width: 100%; box-shadow: none !important; } .no-print { display: none !important; } }`}</style>
      <Stack direction="row" justifyContent="space-between" alignItems="flex-start" sx={{ mb: 2 }}>
        <Box>
          <Typography variant="h6" fontWeight={900}>{title}</Typography>
          <Typography variant="body2">Institution: {global1.collegename || global1.institution || ""}</Typography>
          <Typography variant="body2">Generated by: {currentName()}</Typography>
        </Box>
        <Button className="no-print" startIcon={<Print />} variant="outlined" onClick={() => window.print()}>Print</Button>
      </Stack>
      <Divider sx={{ mb: 2 }} />
      {children}
    </Paper>
  );
}

function ItemsEditor({ items, setItems }) {
  const [item, setItem] = useState(null);
  const [qty, setQty] = useState(1);
  const [masters, setMasters] = useState([]);
  useEffect(() => { getRows("itemmasterds2").then(setMasters); }, []);
  const add = () => {
    if (!item) return;
    setItems([...items, {
      itemid: item._id,
      itemcode: item.itemcode,
      itemname: item.itemname,
      category: item.category,
      itemtype: item.itemtype,
      unit: item.unit,
      quantity: num(qty),
      approvedquantity: 0,
      issuedquantity: 0,
      remarks: ""
    }]);
    setItem(null);
    setQty(1);
  };
  return (
    <Paper sx={{ p: 2 }}>
      <Grid container spacing={2} alignItems="center">
        <Grid item xs={12} md={7}>
          <Autocomplete options={masters} value={item} onChange={(_, value) => setItem(value)} getOptionLabel={(option) => `${option.itemcode || ""} ${option.itemname || ""} ${option.category ? `(${option.category})` : ""}`} renderInput={(params) => <TextField {...params} label="Search item" size="small" />} />
        </Grid>
        <Grid item xs={12} md={2}><TextField size="small" type="number" label="Quantity" value={qty} onChange={(e) => setQty(e.target.value)} fullWidth /></Grid>
        <Grid item xs={12} md={2}><Button startIcon={<Add />} variant="contained" onClick={add}>Add item</Button></Grid>
      </Grid>
      <DataGrid sx={{ mt: 2 }} autoHeight density="compact" rows={items.map((row, index) => ({ ...row, id: index }))} columns={[
        { field: "itemcode", headerName: "Code", width: 130 },
        { field: "itemname", headerName: "Item", flex: 1, minWidth: 180 },
        { field: "category", headerName: "Category", width: 140 },
        { field: "unit", headerName: "Unit", width: 100 },
        { field: "quantity", headerName: "Qty", width: 110, type: "number" },
        { field: "actions", headerName: "Action", width: 110, renderCell: (params) => <Button color="error" size="small" onClick={() => setItems(items.filter((_, idx) => idx !== params.row.id))}>Remove</Button> }
      ]} />
    </Paper>
  );
}

function usePurchase2Basics() {
  const [departments, setDepartments] = useState([]);
  const [stores, setStores] = useState([]);
  const [storeAccess, setStoreAccess] = useState([]);
  const [error, setError] = useState("");
  const load = async () => {
    try {
      const [deptRows, storeRows, accessRows] = await Promise.all([getRows("departmentindentds2"), getRows("storemasterds2"), getRows("storeusersds2")]);
      setDepartments(deptRows);
      setStoreAccess(accessRows);
      const email = text(global1.user).toLowerCase();
      const allowedIds = new Set(accessRows.filter((row) => [row.userid, row.user, row.storeuser].map((v) => text(v).toLowerCase()).includes(email)).map((row) => text(row.storeid)));
      const allowedNames = new Set(accessRows.filter((row) => [row.userid, row.user, row.storeuser].map((v) => text(v).toLowerCase()).includes(email)).map((row) => text(row.store)));
      setStores(storeRows.filter((store) => allowedIds.has(text(store._id)) || allowedIds.has(text(store.storeid)) || allowedNames.has(text(store.storename)) || !accessRows.length));
    } catch (err) {
      setError(err.response?.data?.message || err.message);
    }
  };
  useEffect(() => { load(); }, []);
  return { departments, stores, storeAccess, reloadBasics: load, basicsError: error };
}

export function Purchase2IndentRequestPage() {
  const { departments, stores, basicsError } = usePurchase2Basics();
  const [form, setForm] = useState({ year: "2026-27", departmentname: "", storeid: "", store: "", reqstatus: "Draft", reqdate: today() });
  const [items, setItems] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const save = async (status = form.reqstatus) => {
    try {
      if (!form.departmentname || !form.storeid || !items.length) throw new Error("Select department, store and at least one item");
      const reqid = key("IND");
      const header = await saveRow("storerequisitionds2", { ...form, reqstatus: status, reqid, requestno: reqid, requestedby: currentName(), requestedbyemail: currentUser() });
      await Promise.all(items.map((item) => saveRow("storerequisitionitemsds2", { ...item, requisitionid: header._id, reqid, status })));
      setMessage("Indent request saved");
      setPrintData({ header, items });
    } catch (err) {
      setError(err.message);
    }
  };
  return (
    <Page title="Indent Request" subtitle="Request items from stores assigned to the logged-in user." message={message} error={error || basicsError}>
      <Paper sx={{ p: 2, mb: 2 }}>
        <Grid container spacing={2}>
          <Grid item xs={12} md={3}><Autocomplete options={departments} getOptionLabel={(o) => o.department || o.departmentcode || ""} onChange={(_, v) => setForm((p) => ({ ...p, departmentname: v?.department || "", departmentcode: v?.departmentcode || "" }))} renderInput={(params) => <TextField {...params} label="Department" size="small" />} /></Grid>
          <Grid item xs={12} md={3}><Autocomplete options={stores} getOptionLabel={(o) => o.storename || o.name || ""} onChange={(_, v) => setForm((p) => ({ ...p, storeid: v?._id || v?.storeid || "", store: v?.storename || "" }))} renderInput={(params) => <TextField {...params} label="Assigned store" size="small" />} /></Grid>
          <Grid item xs={12} md={2}><TextField size="small" type="date" label="Request date" value={form.reqdate} InputLabelProps={{ shrink: true }} onChange={(e) => setForm((p) => ({ ...p, reqdate: e.target.value }))} fullWidth /></Grid>
          <Grid item xs={12} md={2}><TextField select size="small" label="Status" value={form.reqstatus} onChange={(e) => setForm((p) => ({ ...p, reqstatus: e.target.value }))} fullWidth>{statusOptions.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid>
        </Grid>
      </Paper>
      <ItemsEditor items={items} setItems={setItems} />
      <Stack direction="row" spacing={1} sx={{ mt: 2 }}><Button startIcon={<Save />} variant="contained" onClick={() => save("Draft")}>Save draft</Button><Button variant="contained" color="success" onClick={() => save("Submitted")}>Submit</Button></Stack>
      <PrintBlock title="Indent Request" data={printData}>
        <Typography>Request: {printData?.header?.requestno || printData?.header?.reqid}</Typography>
        <Typography>Department: {form.departmentname}</Typography>
        <Typography>Store: {form.store}</Typography>
        <DataGrid autoHeight hideFooter rows={(printData?.items || []).map((r, i) => ({ ...r, id: i }))} columns={[{ field: "itemcode", headerName: "Code", width: 130 }, { field: "itemname", headerName: "Item", flex: 1 }, { field: "quantity", headerName: "Qty", width: 100 }]} />
      </PrintBlock>
    </Page>
  );
}

export function Purchase2StoreRequestReviewPage() {
  const { stores, basicsError } = usePurchase2Basics();
  const [requests, setRequests] = useState([]);
  const [selected, setSelected] = useState(null);
  const [items, setItems] = useState([]);
  const [stock, setStock] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const load = async () => {
    const storeIds = new Set(stores.map((s) => text(s._id || s.storeid)));
    const storeNames = new Set(stores.map((s) => text(s.storename)));
    const [reqRows, stockRows] = await Promise.all([getRows("storerequisitionds2"), getRows("storeitemsds2")]);
    setRequests(reqRows.filter((r) => storeIds.has(text(r.storeid)) || storeNames.has(text(r.store))));
    setStock(stockRows);
  };
  useEffect(() => { if (stores.length) load(); }, [stores.length]);
  const open = async (row) => {
    setSelected(row);
    const child = await getRows("storerequisitionitemsds2", [{ field: "requisitionid", value: row._id }]);
    setItems(child.length ? child : [{ ...row, requisitionid: row._id, quantity: row.quantity }]);
  };
  const issue = async () => {
    try {
      for (const item of items) {
        const available = stock.find((s) => text(s.storeid) === text(selected.storeid) && text(s.itemcode) === text(item.itemcode));
        const issueQty = Math.min(num(item.approvedquantity || item.quantity), num(available?.quantity));
        if (issueQty <= 0) continue;
        await updateRow("storeitemsds2", available, { quantity: num(available.quantity) - issueQty });
        if (item._id) await updateRow("storerequisitionitemsds2", item, { approvedquantity: issueQty, issuedquantity: issueQty, status: "Issued" });
      }
      const header = await updateRow("storerequisitionds2", selected, { reqstatus: "Issued" });
      setMessage("Items issued and stock updated");
      setPrintData({ header, items });
      await load();
    } catch (err) { setError(err.message); }
  };
  return (
    <Page title="Store Request Review and Issue" subtitle="Review requests for assigned stores and issue available items." message={message} error={error || basicsError}>
      <Paper sx={{ p: 2 }}><Button startIcon={<Refresh />} onClick={load}>Refresh</Button><DataGrid sx={{ mt: 1 }} autoHeight rows={requests.map((r) => ({ ...r, id: r._id }))} columns={[{ field: "reqdate", headerName: "Date", width: 130 }, { field: "departmentname", headerName: "Department", width: 180 }, { field: "store", headerName: "Store", width: 180 }, { field: "reqstatus", headerName: "Status", width: 130 }, { field: "actions", headerName: "Action", width: 120, renderCell: (p) => <Button size="small" onClick={() => open(p.row)}>Open</Button> }]} slots={{ toolbar: GridToolbar }} /></Paper>
      {selected && <Paper sx={{ p: 2, mt: 2 }}><Typography variant="h6">Issue items</Typography><DataGrid autoHeight rows={items.map((item, i) => ({ ...item, id: i, available: stock.find((s) => text(s.storeid) === text(selected.storeid) && text(s.itemcode) === text(item.itemcode))?.quantity || 0 }))} columns={[{ field: "itemname", headerName: "Item", flex: 1 }, { field: "quantity", headerName: "Requested", width: 120 }, { field: "available", headerName: "Available", width: 120 }, { field: "approvedquantity", headerName: "Issue qty", width: 130, editable: true }]} processRowUpdate={(row) => { setItems(items.map((it, idx) => idx === row.id ? { ...it, approvedquantity: row.approvedquantity } : it)); return row; }} /><Button sx={{ mt: 2 }} variant="contained" onClick={issue}>Issue selected quantities</Button></Paper>}
      <PrintBlock title="Issue / Assignment Document" data={printData}><Typography>Request: {printData?.header?._id}</Typography><Typography>Status: Issued</Typography></PrintBlock>
    </Page>
  );
}

export function Purchase2StorePrRequestPage() {
  const { stores, basicsError } = usePurchase2Basics();
  const [form, setForm] = useState({ storeid: "", storename: "", requestdate: today(), priority: "Normal", status: "Draft", remarks: "" });
  const [items, setItems] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const save = async () => {
    try {
      if (!form.storeid || !items.length) throw new Error("Select store and add items");
      const prnumber = key("PR");
      const header = await saveRow("storeprrequestds2", { ...form, prnumber, requestedby: currentName(), requestedbyemail: currentUser(), status: "Submitted", totalamount: items.reduce((s, i) => s + num(i.estimatedtotal), 0) });
      await Promise.all(items.map((item) => saveRow("storeprrequestitemsds2", { ...item, prnumber, prrequestid: header._id, estimatedtotal: num(item.quantity) * num(item.estimatedprice) })));
      setMessage("PR request submitted");
      setPrintData({ header, items });
    } catch (err) { setError(err.message); }
  };
  return (
    <Page title="Store PR Request" subtitle="Create purchase requisition requests from assigned stores." message={message} error={error || basicsError}>
      <Paper sx={{ p: 2, mb: 2 }}><Grid container spacing={2}><Grid item xs={12} md={4}><Autocomplete options={stores} getOptionLabel={(o) => o.storename || ""} onChange={(_, v) => setForm((p) => ({ ...p, storeid: v?._id || v?.storeid || "", storename: v?.storename || "" }))} renderInput={(params) => <TextField {...params} label="Assigned store" size="small" />} /></Grid><Grid item xs={12} md={2}><TextField size="small" type="date" label="Date" value={form.requestdate} InputLabelProps={{ shrink: true }} onChange={(e) => setForm((p) => ({ ...p, requestdate: e.target.value }))} fullWidth /></Grid><Grid item xs={12} md={2}><TextField size="small" label="Priority" value={form.priority} onChange={(e) => setForm((p) => ({ ...p, priority: e.target.value }))} fullWidth /></Grid></Grid></Paper>
      <ItemsEditor items={items} setItems={setItems} />
      <Button sx={{ mt: 2 }} startIcon={<Save />} variant="contained" onClick={save}>Submit PR</Button>
      <PrintBlock title="Purchase Requisition" data={printData}><Typography>PR: {printData?.header?.prnumber}</Typography><Typography>Store: {form.storename}</Typography></PrintBlock>
    </Page>
  );
}

export function Purchase2PoAssignmentPage() {
  const [prs, setPrs] = useState([]);
  const [users, setUsers] = useState([]);
  const [selected, setSelected] = useState([]);
  const [assignee, setAssignee] = useState(null);
  const [remarks, setRemarks] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const load = async () => {
    const [prRows, userRes] = await Promise.all([getRows("storeprrequestds2"), ep1.get("/api/v2/hrattendance/options", { params: { colid: global1.colid } })]);
    setPrs(prRows);
    setUsers(userRes.data?.users || []);
  };
  useEffect(() => { load(); }, []);
  const assign = async () => {
    try {
      if (!selected.length || !assignee) throw new Error("Select PR requests and assignee");
      await Promise.all(selected.map((id) => {
        const row = prs.find((pr) => pr._id === id);
        return saveRow("storepoassignmentds2", { requestid: id, prnumber: row?.prnumber, assignedto: assignee.name, assignedtoemail: assignee.email || assignee.user, assignedby: currentName(), assignedbyemail: currentUser(), assigneddate: today(), status: "Assigned", remarks });
      }));
      setMessage("PR requests assigned for PO creation");
      setSelected([]);
    } catch (err) { setError(err.message); }
  };
  return <Page title="Assign Store Requests for PO Creation" subtitle="Assign approved store PR requests to PO creators." message={message} error={error}><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2}><Autocomplete sx={{ minWidth: 320 }} options={users} getOptionLabel={(o) => `${o.name || ""} ${o.email || o.user || ""}`} value={assignee} onChange={(_, v) => setAssignee(v)} renderInput={(params) => <TextField {...params} label="PO creator" size="small" />} /><TextField size="small" label="Remarks" value={remarks} onChange={(e) => setRemarks(e.target.value)} /><Button variant="contained" onClick={assign}>Assign</Button></Stack></Paper><Paper sx={{ p: 2 }}><DataGrid autoHeight checkboxSelection rowSelectionModel={selected} onRowSelectionModelChange={setSelected} rows={prs.map((r) => ({ ...r, id: r._id }))} columns={[{ field: "prnumber", headerName: "PR", width: 180 }, { field: "storename", headerName: "Store", width: 180 }, { field: "status", headerName: "Status", width: 130 }, { field: "requestdate", headerName: "Date", width: 130 }, { field: "remarks", headerName: "Remarks", flex: 1 }]} slots={{ toolbar: GridToolbar }} /></Paper></Page>;
}

export function Purchase2LocalPoPage() {
  const [assignments, setAssignments] = useState([]);
  const [vendors, setVendors] = useState([]);
  const [selected, setSelected] = useState(null);
  const [vendor, setVendor] = useState(null);
  const [items, setItems] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const load = async () => {
    const [ass, ven] = await Promise.all([getRows("storepoassignmentds2"), getRows("vendorsds2")]);
    const email = text(global1.user).toLowerCase();
    setAssignments(ass.filter((row) => !row.assignedtoemail || text(row.assignedtoemail).toLowerCase() === email));
    setVendors(ven);
  };
  useEffect(() => { load(); }, []);
  const open = async (row) => {
    setSelected(row);
    setItems(await getRows("storeprrequestitemsds2", [{ field: "prnumber", value: row.prnumber }]));
  };
  const createPo = async () => {
    try {
      if (!selected || !vendor || !items.length) throw new Error("Select assignment, vendor and items");
      const poid = key("PO");
      const priced = await Promise.all(items.map(async (item) => {
        const rates = await getRows("vendoritemsds2", [{ field: "vendorid", value: vendor._id }, { field: "itemid", value: item.itemid }]);
        const rate = rates[0]?.price || item.estimatedprice || 0;
        return { ...item, price: rate, total: num(rate) * num(item.quantity) };
      }));
      const total = priced.reduce((sum, item) => sum + num(item.total), 0);
      const header = await saveRow("storepoorderds2", { poid, year: "2026-27", vendor: vendor.vendorname, vendorid: vendor._id, price: total, netprice: total, actualAmount: total, poType: "Local", postatus: "Delivery Scheduled", approvalStatus: "Approved", deliveryType: "Physical Delivery", description: `Local PO from ${selected.prnumber}` });
      await Promise.all(priced.map((item) => saveRow("storepoitemsds2", { ...item, poid, vendor: vendor.vendorname, vendorid: vendor._id, postatus: "Delivery Scheduled", storereqid: selected.requestid })));
      await updateRow("storepoassignmentds2", selected, { status: "PO Created", poid });
      setMessage("Local PO created and scheduled for delivery");
      setPrintData({ header, items: priced });
    } catch (err) { setError(err.message); }
  };
  return <Page title="Local PO Creation" subtitle="Create local purchase orders from assigned PR requests." message={message} error={error}><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2}><Autocomplete sx={{ minWidth: 320 }} options={assignments} getOptionLabel={(o) => `${o.prnumber || ""} - ${o.status || ""}`} onChange={(_, v) => open(v)} renderInput={(params) => <TextField {...params} label="Assigned PR" size="small" />} /><Autocomplete sx={{ minWidth: 320 }} options={vendors} getOptionLabel={(o) => o.vendorname || o.name || ""} value={vendor} onChange={(_, v) => setVendor(v)} renderInput={(params) => <TextField {...params} label="Vendor" size="small" />} /><Button variant="contained" onClick={createPo}>Create PO</Button></Stack></Paper><Paper sx={{ p: 2 }}><DataGrid autoHeight rows={items.map((r, i) => ({ ...r, id: i }))} columns={[{ field: "itemname", headerName: "Item", flex: 1 }, { field: "quantity", headerName: "Qty", width: 100 }, { field: "estimatedprice", headerName: "Est. price", width: 130 }]} /></Paper><PrintBlock title="Purchase Order" data={printData}><Typography>PO: {printData?.header?.poid}</Typography><Typography>Vendor: {vendor?.vendorname}</Typography></PrintBlock></Page>;
}

export function Purchase2GatePassPage() {
  const [pos, setPos] = useState([]);
  const [selected, setSelected] = useState(null);
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ receiveddate: today(), vehicle: "", challanno: "", invoiceno: "" });
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { getRows("storepoorderds2").then((rows) => setPos(rows.filter((po) => ["Approved", "Delivery Scheduled"].includes(po.approvalStatus) || ["Approved", "Delivery Scheduled"].includes(po.postatus)))); }, []);
  const open = async (po) => { setSelected(po); setItems(await getRows("storepoitemsds2", [{ field: "poid", value: po.poid }])); };
  const save = async () => {
    try {
      const gatepassno = key("GP");
      const header = await saveRow("storegatepassds2", { ...form, gatepassno, poid: selected.poid, vendorid: selected.vendorid, vendorname: selected.vendor, storeid: selected.storeid, storename: selected.storename, receivedby: currentName(), status: "Received" });
      await Promise.all(items.map((item) => saveRow("storegatepassitemsds2", { gatepassno, poid: selected.poid, itemid: item.itemid, itemcode: item.itemcode, itemname: item.itemname, orderedquantity: item.quantity, receivedquantity: item.quantity, unit: item.unit })));
      setMessage("Gate pass created");
      setPrintData({ header, items });
    } catch (err) { setError(err.message); }
  };
  return <Page title="PO Gate Pass" subtitle="Create gate pass records for approved POs." message={message} error={error}><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2}><Autocomplete sx={{ minWidth: 320 }} options={pos} getOptionLabel={(o) => `${o.poid || ""} - ${o.vendor || ""}`} onChange={(_, v) => open(v)} renderInput={(params) => <TextField {...params} label="Approved PO" size="small" />} />{["vehicle", "challanno", "invoiceno"].map((f) => <TextField key={f} size="small" label={f} value={form[f]} onChange={(e) => setForm((p) => ({ ...p, [f]: e.target.value }))} />)}<Button variant="contained" onClick={save} disabled={!selected}>Create gate pass</Button></Stack></Paper><DataGrid autoHeight rows={items.map((r, i) => ({ ...r, id: i }))} columns={[{ field: "itemname", headerName: "Item", flex: 1 }, { field: "quantity", headerName: "Qty", width: 120 }]} /><PrintBlock title="Gate Pass" data={printData}><Typography>Gate pass: {printData?.header?.gatepassno}</Typography></PrintBlock></Page>;
}

export function Purchase2QualityCheckPage() {
  const [passes, setPasses] = useState([]);
  const [selected, setSelected] = useState(null);
  const [items, setItems] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { getRows("storegatepassds2").then(setPasses); }, []);
  const open = async (gp) => {
    setSelected(gp);
    const gpItems = await getRows("storegatepassitemsds2", [{ field: "gatepassno", value: gp.gatepassno }]);
    setItems(gpItems.map((item) => ({ ...item, receivedquantity: item.receivedquantity || item.orderedquantity || 0, approvedquantity: item.receivedquantity || 0, rejectedquantity: 0, returnedquantity: 0, status: "Approved" })));
  };
  const save = async () => {
    try {
      const qcno = key("QC");
      const header = await saveRow("storequalitycheckds2", { qcno, gatepassno: selected.gatepassno, poid: selected.poid, checkedby: currentName(), checkedbyemail: currentUser(), checkdate: today(), status: "QC Done" });
      for (const item of items) {
        await saveRow("storequalitycheckitemsds2", { ...item, qcno });
        const stocks = await getRows("storeitemsds2", [{ field: "storeid", value: selected.storeid || selected.storeId || "" }, { field: "itemcode", value: item.itemcode }]);
        if (stocks[0]) await updateRow("storeitemsds2", stocks[0], { quantity: num(stocks[0].quantity) + num(item.approvedquantity) });
        else await saveRow("storeitemsds2", { storeid: selected.storeid, storename: selected.storename, itemcode: item.itemcode, itemname: item.itemname, quantity: item.approvedquantity, unit: item.unit, status: "Active" });
      }
      setMessage("Quality check saved and approved stock updated");
      setPrintData({ header, items });
    } catch (err) { setError(err.message); }
  };
  return <Page title="Quality Check" subtitle="Record received, approved, rejected and returned quantities after gate pass." message={message} error={error}><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2}><Autocomplete sx={{ minWidth: 320 }} options={passes} getOptionLabel={(o) => `${o.gatepassno || ""} - ${o.poid || ""}`} onChange={(_, v) => open(v)} renderInput={(params) => <TextField {...params} label="Gate pass" size="small" />} /><Button variant="contained" onClick={save} disabled={!selected}>Save QC</Button></Stack></Paper><DataGrid autoHeight rows={items.map((r, i) => ({ ...r, id: i }))} processRowUpdate={(row) => { setItems(items.map((it, idx) => idx === row.id ? row : it)); return row; }} columns={[{ field: "itemname", headerName: "Item", flex: 1 }, { field: "receivedquantity", headerName: "Received", width: 120, editable: true }, { field: "approvedquantity", headerName: "Approved", width: 120, editable: true }, { field: "rejectedquantity", headerName: "Rejected", width: 120, editable: true }, { field: "returnedquantity", headerName: "Returned", width: 120, editable: true }, { field: "remarks", headerName: "Remarks", flex: 1, editable: true }]} /><PrintBlock title="Quality Check Document" data={printData}><Typography>QC: {printData?.header?.qcno}</Typography></PrintBlock></Page>;
}

export function Purchase2GrnCreationPage() {
  const [qcs, setQcs] = useState([]);
  const [selected, setSelected] = useState(null);
  const [items, setItems] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { getRows("storequalitycheckds2").then((rows) => setQcs(rows.filter((r) => !r.grnno))); }, []);
  const open = async (qc) => { setSelected(qc); setItems(await getRows("storequalitycheckitemsds2", [{ field: "qcno", value: qc.qcno }])); };
  const save = async () => {
    try {
      const grnNo = key("GRN");
      const gp = (await getRows("storegatepassds2", [{ field: "gatepassno", value: selected.gatepassno }]))[0] || {};
      const header = await saveRow("storegrnds2", { grnNo, gatePassNumber: selected.gatepassno || "NA", poid: selected.poid || "NA", vendorName: gp.vendorname || "NA", storeId: gp.storeid || "NA", storeName: gp.storename || "NA", receivedBy: currentName(), grnDate: today(), status: "Pending QC", remarks: `QC ${selected.qcno}` });
      await Promise.all(items.map((item) => saveRow("storegrnitemsds2", { grnno: grnNo, grnid: header._id, poid: selected.poid, itemid: item.itemid, itemcode: item.itemcode, itemname: item.itemname, acceptedquantity: item.approvedquantity, rejectedquantity: item.rejectedquantity, unit: item.unit, remarks: item.remarks })));
      await updateRow("storequalitycheckds2", selected, { grnno: grnNo, status: "GRN Created" });
      setMessage("GRN created");
      setPrintData({ header, items });
    } catch (err) { setError(err.message); }
  };
  return <Page title="GRN Creation" subtitle="Create GRN from approved quality check records." message={message} error={error}><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2}><Autocomplete sx={{ minWidth: 320 }} options={qcs} getOptionLabel={(o) => `${o.qcno || ""} - ${o.poid || ""}`} onChange={(_, v) => open(v)} renderInput={(params) => <TextField {...params} label="Approved QC" size="small" />} /><Button variant="contained" onClick={save} disabled={!selected}>Create GRN</Button></Stack></Paper><DataGrid autoHeight rows={items.map((r, i) => ({ ...r, id: i }))} columns={[{ field: "itemname", headerName: "Item", flex: 1 }, { field: "approvedquantity", headerName: "Accepted", width: 120 }, { field: "rejectedquantity", headerName: "Rejected", width: 120 }]} /><PrintBlock title="Goods Receipt Note" data={printData}><Typography>GRN: {printData?.header?.grnNo}</Typography><Typography>PO: {printData?.header?.poid}</Typography></PrintBlock></Page>;
}
